Controllers/AuthController.cs
using E_Commerce2.Models;
using E_Commerce2.Services.IServices;
using E_Commerce2.UnitOfWorkk;
using E_Commerce2.ViewModels.UserVM_s;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce2.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;
        private readonly IAuthService authService;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly IUnitOfWork unitOfWork;

        public AuthController(UserManager<AppUser> userManager,
                              SignInManager<AppUser> signInManager,
                              IAuthService authService,
                              RoleManager<IdentityRole> roleManager,
                              IUnitOfWork unitOfWork)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.authService = authService;
            this.roleManager = roleManager;
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register(string? returnUrl)
        {
            TempData.Keep("returnUrl");
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async  Task<IActionResult> SaveRegister(UserRegisterVM userVM)
        {
            TempData.Keep("returnUrl");

            if (!ModelState.IsValid) 
            {
                return View("Register", userVM);
            }


            AppUser newUser = authService.MapVMtoModel(userVM);

            var res = await userManager.CreateAsync(newUser, userVM.Password);

            if (!res.Succeeded)
            {
                foreach(var item in res.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }

				return View("Register", userVM);
			}

            var roleAssignRes = await userManager.AddToRoleAsync(newUser, "Customer");

            if(!roleAssignRes.Succeeded)
            {
                foreach (var item in res.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }

				return View("Register", userVM);
			}


            await signInManager.SignInAsync(newUser, false);


            return RedirectToAction("Index", "Home");

        }

        [HttpGet]
        public IActionResult Login(string? returnUrl) 
        {
            TempData["returnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> SaveLogin(UserLoginVM user)
        {
            TempData.Keep("returnUrl");

            if (!ModelState.IsValid) 
                return View("Login", user);
            

            AppUser userExists = await userManager.FindByEmailAsync(user.Email);

            if (userExists == null)
                return View("Login", user);

            bool isValid = await userManager.CheckPasswordAsync(userExists, user.Password);

            if (isValid) 
            {
                await signInManager.SignInAsync(userExists, user.RememberMe);

                if (!string.IsNullOrEmpty((string?)TempData["returnUrl"]))
                    return Redirect((string)TempData["returnUrl"]);

                else return RedirectToAction("Index", "Home");

            }

            return View(user);
        }

        
        public async Task<IActionResult> Logout()
        {
            if(User.Identity.IsAuthenticated)
            {
                await signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        [Authorize]
		public async Task<IActionResult> GetProfile()
		{
            var appUser = await userManager.GetUserAsync(User);

            if (appUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

			var profileVM = authService.MapModelToVM(appUser);

			return View(profileVM);
		}


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> SaveEditProfile(ProfileVM profile)
		{
            if(!ModelState.IsValid)
            {
                ViewData["ErrorMsg"] = "Please enter valid values";
                return View("GetProfile", profile); 
			}


            var appUser = await userManager.GetUserAsync(User);
            var newAppUser = authService.MapVMtoModel(appUser, profile);
            
            var res = await userManager.UpdateAsync(newAppUser);

            if (res.Succeeded) 
            {
                ViewData["SuccessMsg"] = "Update Done Successfully";
            }

            else
            {
                ViewData["ErrorMsg"] = "Unable to update data";
				return View("GetProfile", profile);
			}

            return View("GetProfile", profile);
            

        }

        [HttpGet]
		[Authorize]
		public async Task<IActionResult> ChangePassword()
        {
            return View();
        }

        [HttpPost]
		[AutoValidateAntiforgeryToken]
		[Authorize]
		public async Task<IActionResult> SaveChangePassword(PasswordVM password)
        {
			var appUser = await userManager.GetUserAsync(User);

            if (appUser == null)
            {
				ViewData["ErrorMsg"] = "Unable to update data";
				return View("Index", "Home");
            }

            if (!ModelState.IsValid) 
            {
				ViewData["ErrorMsg"] = "Unable to update data";
				return View("ChangePassword", password);
			}

            var res = await userManager.ChangePasswordAsync(appUser, password.CurrentPassword, password.NewPassword);

            if (res.Succeeded) 
            {
                ViewData["SuccessMsg"] = "Password updated successfully";
            }
            else
            {
				ViewData["ErrorMsg"] = "Unable to update data";
				return View("ChangePassword", password);
			}

            return RedirectToAction("Index", "Home");
		}

		





	}
}

Controllers/CartController.cs
using E_Commerce2.Models;
using E_Commerce2.Services.IServices;
using E_Commerce2.UnitOfWorkk;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace E_Commerce2.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly ICartService cartService;
        private readonly UserManager<AppUser> userManager;

        public CartController(IUnitOfWork unitOfWork, ICartService cartService, UserManager<AppUser> userManager)
        {
            this.unitOfWork = unitOfWork;
            this.cartService = cartService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> GetCartById(int id)
        {
            var cart = await unitOfWork.CartRepo.GetByIdAsync(id);
            var cartVM = await cartService.MapCartToVM(cart);

            return View(cartVM);
                         
        }

        public async Task<ActionResult> AddToCart(int ProductId) 
        {
            var UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (UserId == null) ;

            var cart = new Cart();
            cart.ProductId = ProductId;
            cart.CustomerId = UserId;
            cart.quantity = 1;
            cart.UpdatedAt = DateTime.Now;
           
           cart.Customer = await userManager.FindByIdAsync(UserId);
           cart.Product = await unitOfWork.ProductRepo.GetByIdAsync(ProductId);

            await unitOfWork.CartRepo.insertAsync(cart);

            TempData["ProductId"] = "Added";
            
            // Returning to the products view
            return RedirectToAction("GetCartsforUser");
        }


        public async Task<IActionResult> RemoveFromCart(int CartId)
        {
            bool f = await unitOfWork.CartRepo.deleteAsync(CartId);
            ViewBag.ProductId = "Add To Cart";

            return RedirectToAction("GetCartsforUser");
        }


        public async Task<IActionResult> GetCartsforUser()
        {
            var UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (UserId == null);

            var lstCarts = await unitOfWork.CartRepo.GetCartsByUserId(UserId);

            var CartsVM = await cartService.MapCartsToVMs(lstCarts);

            return View(CartsVM);
        }

        public async Task<int> GetCartSize()
        {
            string UserId = User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;

            if (UserId == null);

            var lstCarts = await unitOfWork.CartRepo.GetCartsByUserId(UserId);

            return lstCarts.Count;
        }

        public async Task<IActionResult> IncCartQuantity(int CartID)
        { 
            var cart = await unitOfWork.CartRepo.GetByIdAsync(CartID);
            cart.quantity += 1;
            await unitOfWork.Complete();

            return RedirectToAction("GetCartsforUser");

        }

        public async Task<IActionResult> DecCartQuantity(int CartID)
        {
            var cart = await unitOfWork.CartRepo.GetByIdAsync(CartID);

            if (cart.quantity == 0)
            {
                return RedirectToAction("GetCartsforUser");
            }
           
            cart.quantity -= 1;
            await unitOfWork.Complete();

            return RedirectToAction("GetCartsforUser");
        }


        public async Task<bool> IsProductInCart(int productID)
        {
            string userId = User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? string.Empty;

            bool check = await cartService.inCart(productID, userId);
            
            if(check) ViewBag.IsProductInCart = true;
            else ViewBag.IsProductInCart = false;

            return check;
        }



    }
}

Controllers/OrderController.cs
using E_Commerce2.Models;
using E_Commerce2.Services.IServices;
using E_Commerce2.UnitOfWorkk;
using E_Commerce2.ViewModels.CartVM_s;
using E_Commerce2.ViewModels.OderVM_s;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Stripe;
using System.Security.Claims;

namespace E_Commerce2.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IOrderService orderService;

        public OrderController(IUnitOfWork unitOfWork, IOrderService orderService)
        {
            this.unitOfWork = unitOfWork;
            this.orderService = orderService;
        }

        [HttpPost]
        public IActionResult CheckOut(List<CartVM> cartItems)
        {
            TempData["CartData"] = JsonConvert.SerializeObject(cartItems);
            TempData.Keep();

            if(!cartItems.Any())
                Console.WriteLine("HAHAHA");

            decimal SubTotal = cartItems.Sum(x => x.Quantity * x.Price);

            TempData["SubTotal"] = JsonConvert.SerializeObject(SubTotal); 
            TempData.Keep();

            Console.WriteLine(SubTotal);

            ViewBag.SubTotal = SubTotal;


            return View("CheckOut");

        }

        [HttpPost]
        public async Task<IActionResult> CreateOrder(OrderVM order)
        {

            TempData.Keep("CartData");
            TempData.Keep("SubTotal");

            string userId = User?.FindFirstValue(ClaimTypes.NameIdentifier) ?? "0";

            using var trx = await unitOfWork.BeginTransaction();
            {

                try
                {
                    Order ord = await orderService.CreateOrder(order, userId, (decimal)order.SubTotal);

                    var cartDataJson = TempData["CartData"] as string;

                    if (cartDataJson == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    var cartItems = JsonConvert.DeserializeObject<List<CartVM>>(cartDataJson);

                    var orderItems = await orderService.InsertOrderItems(cartItems, ord.Id);

                    ord.Items = orderItems;
                    await unitOfWork.Complete();


                    await trx.CommitAsync();

                    return RedirectToAction("CreatePaymentSession", "Payment", new { id = ord.Id });
                }
                catch
                {
                    await trx.RollbackAsync();
                    return RedirectToAction("Index", "Home");
                }


            };

        }

        
        //public async Task<IActionResult> ConfirmOrder(int id)
        //{
        //
        //   var Order = await unitOfWork.OrderRepo.GetByIdAsync(id);
        //   Order.OrderStatus = "Confirmed";
        //   await unitOfWork.Complete();
        //
        //   return View();
        //}
         


        public async Task<IActionResult> CancelOrder(int id)
        {
            var Order = await unitOfWork.OrderRepo.GetByIdAsync(id);

            if (Order == null) return NotFound();

            await RefundOrder(Order.PaymentIntentId);

            Console.WriteLine(Order.PaymentIntentId);

            Order.OrderStatus = "Canceled";

            await unitOfWork.Complete();

            return View();
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ShipOrder(int id)
        {
            var Order = await unitOfWork.OrderRepo.GetByIdAsync(id);

            if (Order == null) return NotFound();

            Order.OrderStatus = "Shipped";

            await unitOfWork.Complete();

            return View("GetShippedOrders");

        }

        public async Task<IActionResult> GetOrdersByUserId()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId == null) return NotFound();

            var orders = await unitOfWork.OrderRepo.GetOrdersByUserID(userId);

            return View(orders);
            
        }

        public async Task<IActionResult> GetOrderByID(int id)
        {

            //GetOrderItemsByOrderId(int id)
            var Order = await unitOfWork.OrderRepo.GetOrderItemsByOrderId(id);
            return View(Order);
        }

       
        public async Task RefundOrder(string intentId)
        {
            var RefundOptions = new RefundCreateOptions()
            {
                PaymentIntent = intentId,
            };

            var RefundService = new RefundService();
            await RefundService.CreateAsync(RefundOptions);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Shop Now</title>
    <link rel="icon" href="/Images/icon.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Commerce2.styles.css" asp-append-version="true" />
	<link href="~/css/stylesii.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/Images/icon.png" alt="..." width="30" class="me-2" /> ShopMe!
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="GetNewestProducts">Store</a>
                        </li>
                    </ul>
                </div>


                <ul class="navbar-nav me-2">
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="GetCartsforUser">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1h1a.5.5 0 0 1 .485.379L2.89 6H14a.5.5 0 0 1 .49.598l-1.5 8A.5.5 0 0 1 12.5 15H4a.5.5 0 0 1-.491-.408L1.01 3H.5a.5.5 0 0 1-.5-.5zm3.14 5L4.89 13h7.72l1.28-6H3.14zM5 14a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm6 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
</svg>
                                
                            </a>
                        </li>
                    </ul>

                @if(!User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="btn btn-outline-primary me-2" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    </ul>
                }

                @if(User.IsInRole("Admin"))
                {
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                admin
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>

                                <li><a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="GetProfile">Profile</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="GetAllUsers">Users</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="AddNewAdmin">Add Admin</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                }
                else if(User.Identity.IsAuthenticated)
                {


                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @( User.Identity.Name + " (Customer)")
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="GetOrdersByUserId">Orders</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="GetProfile">Profile</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                }

               

            </div>
        </nav>
    </header>

    @if (ViewData["HomePage"] == null)
    {
        <div class="container mt-3">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }
    else
    {
        @RenderBody()
    }

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - E_Commerce2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/js/scriptsii.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>